### ISSUE TITLE
KeyError: 'author'

### ISSUE THREAD

**Issue by Qlupic** [snatchface13/onlyfans#1]
Something seems to be broken at the moment. But not for all profiles.

Here is an example:

```
Scrape Processing
Name: ssunbiki
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "S:\SHARE\Project1\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "S:\SHARE\Project1\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "S:\SHARE\Project1\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "S:\SHARE\Project1\OnlyFans-master\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "S:\SHARE\Project1\OnlyFans-master\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "S:\SHARE\Project1\OnlyFans-master\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "S:\SHARE\Project1\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "S:\SHARE\Project1\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "S:\SHARE\Project1\OnlyFans-master\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'
```

The exact same settings are working for other profiles.

**Comment by ghost** [comment]
I'm getting the same error on one user as well.

**Comment by Qlupic** [comment]
Just realized this repo is dead and the new owner/s are located on a different Github profile. Never mind this issue.
